'use client'

import React, { useState, useRef } from 'react'
import { Button, Input, addToast, cn } from '@heroui/react'
import Icon from '@/components/icon'
import { useRouter, useSearchParams } from 'next/navigation'
import { api } from '@/api/generated/main-service'
import { handleApiError } from '@/hooks/useApiError'

const ACCEPTED = '.docx,.xlsx'
const VALID_EXTS = ['.docx', '.xlsx']

const getFileType = (name: string) => {
  const ext = '.' + name.split('.').pop()?.toLowerCase()
  return ext === '.xlsx' ? 'excel' : 'pdf'
}

import { Suspense } from 'react'

function CreateTemplatePage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const projectId = searchParams.get('projectId')

  const [templateName, setTemplateName] = useState('')
  const [templateKey, setTemplateKey] = useState('')
  const [uploadedFile, setUploadedFile] = useState<File | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [isGeneratingKey, setIsGeneratingKey] = useState(false)
  const [isDragOver, setIsDragOver] = useState(false)
  const [showErrors, setShowErrors] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const goBack = () => {
    router.push(projectId ? `/project/${projectId}/templates` : '/templates')
  }

  const generateKey = async () => {
    setIsGeneratingKey(true)
    try {
      const key = await api.templates.templateGenerateKeyList()
      setTemplateKey(key)
    } catch (err) {
      handleApiError(err, 'Failed to generate key.')
    } finally {
      setIsGeneratingKey(false)
    }
  }

  const validateAndSetFile = (file: File) => {
    const ext = '.' + file.name.split('.').pop()?.toLowerCase()
    if (!VALID_EXTS.includes(ext)) {
      addToast({
        title: 'Unsupported file type',
        description: 'Please upload a .docx or .xlsx file',
        color: 'danger'
      })
      return
    }
    setUploadedFile(file)
    if (!templateName) setTemplateName(file.name.replace(/\.[^/.]+$/, ''))
  }

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) validateAndSetFile(e.target.files[0])
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragOver(false)
    if (e.dataTransfer.files?.[0]) validateAndSetFile(e.dataTransfer.files[0])
  }

  const clearFile = () => {
    setUploadedFile(null)
    if (fileInputRef.current) fileInputRef.current.value = ''
  }

  const handleCreate = async () => {
    if (!uploadedFile || !templateName.trim()) {
      setShowErrors(true)
      addToast({ title: 'Fill in all required fields', color: 'danger' })
      return
    }

    setIsLoading(true)
    try {
      const response = await api.templates.templatesCreate(
        {
          name: templateName,
          templateKey: templateKey || undefined,
          project_id: projectId || undefined,
          isAutoGeneratedVariable: true
        },
        { file: uploadedFile }
      )

      if (response?.templateKey) {
        const fileType = getFileType(uploadedFile.name)
        const qs = projectId ? `?projectId=${projectId}` : ''
        const dest =
          fileType === 'excel'
            ? `/excel/templates/${response.templateKey}${qs}`
            : `/pdf/templates/${response.templateKey}${qs}`
        router.replace(dest)
      } else {
        goBack()
      }
    } catch (err) {
      handleApiError(err, 'Failed to create template. Please try again.')
    } finally {
      setIsLoading(false)
    }
  }

  const fileType = uploadedFile ? getFileType(uploadedFile.name) : null

  return (
    <div className='dashboard-page mx-auto w-full max-w-2xl pb-20 pt-4'>
      {/* ── Toolbar ── */}
      <div className='dashboard-panel'>
        <div className='dashboard-header'>
        <button
          onClick={goBack}
          className='flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-default-500 transition-colors hover:bg-content2 hover:text-foreground'
          aria-label='Back to templates'>
          <Icon icon='lucide:arrow-left' className='h-4 w-4' />
        </button>
        <div className='dashboard-icon-box'>
          <Icon icon='lucide:file-plus' className='h-4 w-4 text-primary' />
        </div>
        <div className='min-w-0 flex-1'>
          <h1 className='dashboard-title'>New Template</h1>
          <p className='dashboard-subtitle'>Upload a DOCX or XLSX file and prepare it for generation.</p>
        </div>
        </div>
      </div>

      {/* ── Body ── */}
      <div className='dashboard-panel p-5 md:p-6'>
        <div className='space-y-5'>
          {/* Name */}
          <div>
            <label className='mb-1.5 flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-default-500'>
              Template Name <span className='text-danger'>*</span>
            </label>
            <Input
              size='md'
              variant='flat'
              radius='sm'
              placeholder='e.g. Monthly Invoice'
              value={templateName}
              onValueChange={setTemplateName}
              isInvalid={showErrors && !templateName.trim()}
              errorMessage={showErrors && !templateName.trim() ? 'Required' : ''}
              isDisabled={isLoading}
              autoFocus
              classNames={{
                input: 'font-medium',
                inputWrapper: 'bg-content2 data-[hover=true]:bg-content3 group-data-[focus=true]:bg-content2'
              }}
            />
          </div>

          {/* Upload zone */}
          <div>
            <label className='mb-1.5 flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-default-500'>
              File <span className='text-danger'>*</span>
            </label>
            <div
              className={cn(
                'relative flex min-h-[180px] cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed p-6 transition-all duration-200',
                isDragOver
                  ? 'border-primary bg-primary/10'
                  : showErrors && !uploadedFile
                    ? 'border-danger bg-danger/5'
                    : uploadedFile
                      ? 'cursor-default border-primary/40 bg-content2'
                      : 'border-default-300 bg-content2 hover:border-primary/70 hover:bg-content3',
                isLoading && 'pointer-events-none opacity-50'
              )}
              onDrop={!isLoading && !uploadedFile ? handleDrop : undefined}
              onDragOver={
                !isLoading && !uploadedFile
                  ? e => {
                      e.preventDefault()
                      setIsDragOver(true)
                    }
                  : undefined
              }
              onDragLeave={
                !isLoading && !uploadedFile
                  ? e => {
                      e.preventDefault()
                      setIsDragOver(false)
                    }
                  : undefined
              }
              onClick={() => !isLoading && !uploadedFile && fileInputRef.current?.click()}>
              <input ref={fileInputRef} type='file' className='hidden' accept={ACCEPTED} onChange={handleFileChange} />

              {uploadedFile ? (
                <div className='flex flex-col items-center text-center'>
                  <div
                    className={cn(
                      'mb-3 flex h-12 w-12 shrink-0 items-center justify-center rounded-lg border shadow-sm',
                      fileType === 'excel'
                        ? 'border-success bg-success text-white'
                        : 'border-primary bg-primary text-primary-foreground'
                    )}>
                    <Icon
                      icon={fileType === 'excel' ? 'lucide:file-spreadsheet' : 'lucide:file-check'}
                      className='h-6 w-6'
                    />
                  </div>
                  <p className='text-base font-bold text-foreground'>{uploadedFile.name}</p>
                  <p className='text-xs font-medium text-default-500'>
                    {fileType === 'excel' ? 'Excel Template' : 'Word Template'} /{' '}
                    {(uploadedFile.size / 1024).toFixed(1)} KB
                  </p>
                  <button
                    onClick={e => {
                      e.stopPropagation()
                      clearFile()
                    }}
                    disabled={isLoading}
                    className='mt-3 flex items-center gap-1.5 text-xs font-bold uppercase tracking-wide text-default-400 hover:text-danger disabled:pointer-events-none disabled:opacity-50'>
                    <Icon icon='lucide:x' className='h-3.5 w-3.5' />
                    Remove File
                  </button>
                </div>
              ) : (
                <>
                  <div className='mb-4 flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-content3'>
                    <Icon icon='lucide:upload-cloud' className='h-8 w-8 text-default-400' />
                  </div>
                  <div className='text-center'>
                    <p className='text-lg font-bold text-foreground'>Click to upload or drag and drop</p>
                    <p className='mt-1 text-xs font-medium text-default-500'>
                      DOCX - Word template / XLSX - Excel template
                    </p>
                  </div>
                </>
              )}
            </div>
            {showErrors && !uploadedFile && <p className='mt-1 text-xs text-danger'>Please upload a file</p>}
          </div>

          {/* Auto-detect info (always on) */}
          <div className='dashboard-soft px-3 py-2.5'>
            <div className='flex items-center gap-2'>
              <Icon icon='lucide:scan-search' className='h-6 w-6 shrink-0 text-primary' />
              <div>
                <p className='text-sm font-medium text-foreground'>Auto-detect variables</p>
                <p className='text-xs text-default-500'>
                  Variables like <code className='font-mono'>{`{{name}}`}</code> will be detected from the file and
                  added to the builder automatically.
                </p>
              </div>
            </div>
          </div>

          {/* Custom key (always available) */}
          <div className='dashboard-soft p-4'>
            <p className='mb-2.5 text-xs font-semibold'>
              Custom template key <span className='font-normal text-default-400'>(optional)</span>
            </p>
            <div className='space-y-1.5'>
              <div className='flex gap-2'>
                <Input
                  size='sm'
                  variant='flat'
                  radius='sm'
                  placeholder='e.g. invoice-monthly'
                  value={templateKey}
                  onValueChange={setTemplateKey}
                  isDisabled={isLoading}
                  classNames={{
                    input: 'font-mono text-xs',
                    inputWrapper:
                      'bg-content2 data-[hover=true]:bg-content3 group-data-[focus=true]:bg-content2'
                  }}
                />
                <Button
                  size='sm'
                  variant='flat'
                  radius='sm'
                  onPress={generateKey}
                  isIconOnly
                  isLoading={isGeneratingKey}
                  isDisabled={isLoading}
                  className='shrink-0 bg-content2 text-default-600 hover:bg-content3'>
                  {!isGeneratingKey && <Icon icon='lucide:sparkles' className='h-4 w-4' />}
                </Button>
              </div>
              <p className='text-[11px] text-default-400'>
                Used in API calls as <code className='font-mono text-default-500'>templateKey</code>. Auto-generated if
                left blank.
              </p>
            </div>
          </div>

          {/* ── Actions ── */}
          <div className='flex items-center justify-end gap-2 border-t border-default-100 pt-4'>
            <Button
              size='md'
              variant='flat'
              radius='sm'
              onPress={goBack}
              isDisabled={isLoading}
              className='bg-content2 font-semibold text-default-600 hover:bg-content3'>
              Cancel
            </Button>
            <Button
              color='primary'
              size='md'
              radius='sm'
              onPress={handleCreate}
              isLoading={isLoading}
              startContent={!isLoading && <Icon icon='lucide:plus' className='h-4 w-4' />}
              className='px-6 font-semibold shadow-none'>
              Create Template
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default function CreateTemplatePageWrapper() {
  return (
    <Suspense>
      <CreateTemplatePage />
    </Suspense>
  )
}
